baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Patrick Walsh'
theme = "blowfish"

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3